### ISSUE TITLE
Multiple Layouts

### ISSUE THREAD

**Issue by irvinebroque** [awesomebox/awesomebox-core#1]
Right now, if you specify a layout other than `default`, it is rendered within `default`, rather than instead of default.

We need to be able to support multiple layouts in 0.4.0 - was working before, just got mixed up in the changes from 0.3.

**Comment by irvinebroque** [comment]
@mattinsler - for an example case, take a look at `/testpost` when you pull down Master on Awesomebox Blog:

https://github.com/irvinebroque/awesomebox-blog

I have it commented out right now, but uncomment the layout in the `{{{data}}}` and you should get this error:

200 Error parsing front matter of /testpost.md: post is not defined
at parse_front_matter (/Users/Brendan/code/awesomebox/awesomebox-core/src/lib/awesomebox.coffee:175:15)
at /Users/Brendan/code/awesomebox/awesomebox-core/src/lib/steps.coffee:26:20
at _fulfilled (/Users/Brendan/code/awesomebox/awesomebox-core/src/node_modules/q/q.js:798:54)
at self.promiseDispatch.done (/Users/Brendan/code/awesomebox/awesomebox-core/src/node_modules/q/q.js:827:30)
at Promise.promise.promiseDispatch (/Users/Brendan/code/awesomebox/awesomebox-core/src/node_modules/q/q.js:760:13)
at /Users/Brendan/code/awesomebox/awesomebox-core/src/node_modules/q/q.js:821:14
at flush (/Users/Brendan/code/awesomebox/awesomebox-core/src/node_modules/q/q.js:108:17)
at process._tickCallback (node.js:415:13)
